/*
 * grunt-add-comment
 * https://github.com/PillowPillow/grunt-add-comment
 *
 * Copyright (c) 2014 Nicolas Gaignoux
 * Licensed under the MIT license.
 */

'use strict';

var Path = require('path');

module.exports = function(grunt) {

	// Please see the Grunt documentation for more information regarding task
	// creation: http://gruntjs.com/creating-tasks

	grunt.registerMultiTask('add_comment', 'Prepend or append some comments to your autogenerated files', function() {
		var options = this.options({
			comments: ['autogenerated'],
			carriageReturn: "\n",
			prepend: true,
			syntaxes: {
				'*': '//',
			}
		});

		if(!options.syntaxes['*'])
			options.syntaxes['*'] = '//';

		var comment = '', content, extension, commentSyntax;
		this.files.forEach(function(el) {

			el.src.filter(function(filePath) {
				var witness = grunt.file.exists(filePath);
				if(!witness)
					grunt.log.warn('Source file "' + filePath + '" not found.');

				return witness;
			}).map(function(filePath) {
				content = grunt.file.read(filePath);

				extension = Path.extname(filePath);
				commentSyntax = ( extension in options.syntaxes ? options.syntaxes[extension] : options.syntaxes['*'] ) + ' ';


				comment = '';
				for(var i = 0; i<options.comments.length; i++) {
					comment += commentSyntax + options.comments[i] + options.carriageReturn;
				}

				content = options.prepend ? comment + grunt.file.read(el.src[0]) : grunt.file.read(el.src[0]) + options.carriageReturn + comment;

				grunt.file.write(el.dest, content);
				grunt.log.writeln('File "' + el.dest + '" edited.');
			});
		});
	});

};
